### ISSUE TITLE
Getting 403 create suggestion api - /v1/suggestion/update

### ISSUE THREAD

**Issue by vishal1702** [neon-lab-dev/Postman-collection#11]
Getting 403 response for create suggestion api. 
Updated the token in authorization tab before sending api request.

![suggestion api](https://github.com/neon-lab-dev/Postman-collection/assets/52391313/07922a11-a91a-4d64-804d-81bafbc6702a)

Kindly check.

**Comment by ritik-agrawal** [comment]
Did you try with the by the token created for the user?

cc- @vishal1702

**Comment by vishal1702** [comment]
Yes. Followed below steps
1. Signup api hit to get the token.
2. Updated the token in authorization field. Create Suggestion api request sent, got 403 Forbidden response.

**Comment by ritik-agrawal** [comment]
The above changes has been done in the below Pr
https://github.com/neon-lab-dev/Postman-collection/pull/12

Also rectified the add Product API variable name changes.

cc- @sjha24
